name: Ollama 2nd
on:
  workflow_dispatch:

jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
    - name: Install Ollama
      run: curl -fsSL https://ollama.com/install.sh | sh

    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: pip install ollama

    - name: Run ollama
      run: |
        ollama serve &
        sleep 5 &
        ollama run llama3.2-vision:latest &
        ollama pull llama3.2-vision:latest

    - name: Run Python script
      run: python ollama.py

    
