name: Run Ollama on macOS

on:
  push:
    branches:
      - main

jobs:
  run-ollama:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Homebrew
        run: |
          if ! command -v brew; then
            echo "Installing Homebrew..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          else
            echo "Homebrew already installed"
          fi

      - name: Install Ollama
        run: |
          echo "Installing Ollama..."
          brew install ollama

      - name: Run Ollama model
        run: |
          # Example command to generate text using the "llama2" model
          echo "Running Ollama..."
          ollama run llama2 "请解释这段文字的意思：'中国的历史悠久，文化丰富。'"
